const gaaliMatches = [
    "bc",
    "bsdk",
    "bhosdike",
    "mkc",
    "tmkc",
    "mkl",
    "teri ma ki chut",
    "madarchod",
    "mdrchd",
    "bkc",
    "tbkc",
    "teri bhen ki chut",
    "bhnchd",
    "bhenchod",
    "bkl",
    "bhenklode",
    "dalle",
    "chutiya",
    "randike",
    "randibaz",
    "randibaaz",
    "randi",
    "bhadve",
    "bhosda",
    "chut mari ke",
    "bahinchod"
]

export default gaaliMatches;