const gaali = ['Teri gand mein itna chhed, saala rocket bhi na usmein sedh',
  'Chutiya tera dimaag hai thanda, bolta jaise lund ka anda',
  'Madarchod ki shakal hai teri, dekh ke aankh mein aag bheri',
  'Teri maa ka bhosda itna khula, saala truck bhi andar ghusa hua',
  'Gandu ke pille tera wajood, tatti se bhara hai pura mood',
  'Bhenchod ka dil hai sookha, har baat mein gand ka jhootha',
  'Teri behen ki choot se dhuaan, sungh ke mare kutta bhi huaan',
  'Lauda tera zindagi ka saaz, har jagah failata gand ka raaz',
  'Harami ka baccha tu sasta, dimag mein bas tatti ka vasta',
  'Teri shakal pe thook ka nishaan, dekh ke bhage koi bhi insaan',
  'Chutmarike ka style hai ganda, lund pe baitha hai pura banda',
  'Teri gand se aati hai boo, saala toilet bhi bole ab tu ro',
  'Madarchod ka sapna hai bada, har raat gand mein lund ka jhada',
  'Teri maa ki choot ka mela, har din laude ka naye khela',
  'Gandu tera muh hai bakwas, bolta jaise tatti ka vaas',
  'Bhenchod ki aankh hai laal, gand mein ghusa hai pura maal',
  'Teri behen ka bhosda hai geela, har lauda usmein karta khela',
  'Laude ke bal tera pura scene, dimag mein bas gand ka machine',
  'Harami ka chehra hai tera, dekh ke aankh mein aaye ghera',
  'Teri gand pe laat ka nishaan, cheekh se bhar de pura makaan',
  'Chutiya tera pura khandaan, har ek ke dimag mein tatti ka daan',
  'Madarchod ka muh hai khula, bolta jaise gand mein hua bhula',
  'Teri shakal hai bhosdi ka gola, dekh ke mare kutta bhi bola',
  'Teri maa ka choot ka dhandha, har gali mein laude ka bandha',
  'Gandu ke bacche tera raag, har jagah failata gand ka daag',
  'Bhenchod ka dimaag hai sasta, har baat mein tatti ka vasta',
  'Teri behen ki choot ka keeda, bolti toh lund khada seedha',
  'Lauda tera dimag se khota, har baat mein gand ka quota',
  'Harami ka baap bhi roye, tujhe paida karke regret soye',
  'Teri gand mein itna pressure, saala bolta toh lage fissure',
  'Chutmarike ka pura wajood, tatti se bhara hai zindagi ka mood',
  'Madarchod ka chehra hai ganda, dekh ke lage aankh mein danda',
  'Teri shakal pe tatti ka dher, dekh ke mare koi bhi sher',
  'Teri maa ki choot ka rasta, har din laude ka naye vasta',
  'Gandu tera muh hai pot, bolta toh aaye tatti ka shot',
  'Bhenchod ka sapna hai thanda, gand mein ghusa hai pura banda',
  'Teri behen ka bhosda hai bada, har lauda usmein ghusa pada',
  'Laude ke bal tera zindagi ka plan, har baat mein gand ka scam',
  'Harami ka dil hai khota, dimag mein bas tatti ka kota',
  'Teri gand se badboo itni, saala sungh ke mare kutte ki chhati',
  'Chutiya tera pura zamana, har ek ka dimag hai bakwas thikana',
  'Madarchod ka muh hai sasta, bolta jaise gand ka vasta',
  'Teri shakal pe thook ka paani, dekh ke bhage kutta bhi rani',
  'Teri maa ka choot ka bazaar, har din laude ka naye izhaar',
  'Gandu ke pille tera style, har baat mein tatti ka pile',
  'Bhenchod ka chehra hai thanda, dimag mein bas gand ka ganda',
  'Teri behen ki choot ka gate, har din laude ka naye rate',
  'Lauda tera dimag mein basa, bolta toh tatti ka rasa',
  'Harami ka baccha tu tharki, dimag mein lund ka har ek dharki',
  'Teri gand pe thappad ka zor, saala cheekh se toot jaye mor',
  'Chutmarike tera pura scene, har jagah gand ka machine',
  'Madarchod ka dil hai sookha, har baat mein tatti ka jhootha',
  'Teri shakal hai suwar ka thobda, dekh ke bhage koi bhi lobda',
  'Teri maa ka choot ka jhada, har din laude ka pura pada',
  'Gandu tera muh hai khula, bolta toh gand mein hua bhula',
  'Bhenchod ka dimaag hai geela, har baat mein tatti ka khela',
  'Teri behen ka bhosda hai sasta, har lauda usmein karta masta',
  'Laude ke bal tera pura raag, har jagah gand ka naye daag',
  'Harami ka chehra hai khota, dekh ke aankh mein lage chhota',
  'Teri gand mein itna keeda, saala bolta toh lage seedha',
  'Chutiya tera pura sapna, har baat mein tatti ka apna',
  'Madarchod ka muh hai thanda, bolta jaise gand ka ganda',
  'Teri shakal pe laat ka zor, dekh ke mare kutta bhi chor',
  'Teri maa ki choot ka paani, laude ke liye hai free ka khazana',
  'Gandu ke bacche tera wajood, tatti se bhara hai pura mood',
  'Bhenchod ka dil hai khali, har jagah gand ka naye jali',
  'Teri behen ki choot ka dhoka, har baar laude se tu thoka',
  'Lauda tera zindagi ka raja, har baat mein tatti ka saaja',
  'Harami ka sapna hai chhota, dimag mein bas gand ka kota',
  'Teri gand se aati hai awaaz, saala sunke mare kutta saaz',
  'Chutmarike ka pura plan, har baat mein gand ka scam',
  'Madarchod ka chehra hai sasta, dekh ke aankh mein lage vasta',
  'Teri shakal hai bhosdi ka thobda, dekh ke mare koi bhi lobda',
  'Teri maa ka choot ka nasha, har din laude ka pura tasa',
  'Gandu tera muh hai geela, bolta toh tatti ka khela',
  'Bhenchod ka dimaag hai thoka, har baat mein gand ka dhoka',
  'Teri behen ka bhosda hai khula, har lauda usmein ghusa bhula',
  'Laude ke bal tera pura zamana, har jagah tatti ka thikana',
  'Harami ka baccha tu ganda, dimag mein bas tatti ka banda',
  'Teri gand pe thappad ka nishaan, saala cheekh se bhar de makaan',
  'Chutiya tera pura scene, har baat mein gand ka machine',
  'Madarchod ka muh hai khota, bolta jaise tatti ka quota',
  'Teri shakal pe tatti ka paani, dekh ke bhage kutta bhi rani',
  'Teri maa ki choot ka gate, har din laude ka naye fate',
  'Gandu ke pille tera raag, har jagah gand ka naye daag',
  'Bhenchod ka chehra hai geela, dimag mein tatti ka khela',
  'Teri behen ki choot ka mela, har lauda usmein karta khela',
  'Lauda tera dimag se sasta, har baat mein tatti ka vasta',
  'Harami ka dil hai thanda, dimag mein bas gand ka ganda',
  'Teri gand mein itna zor, saala bolta toh lage chor',
  'Chutmarike ka pura wajood, tatti se bhara hai zindagi ka mood',
  'Madarchod ka sapna hai khota, har baat mein gand ka kota',
  'Teri shakal hai suwar ka gola, dekh ke mare kutta bhi bola',
  'Teri maa ka choot ka rasta, har din laude ka pura vasta',
  'Gandu tera muh hai thanda, bolta jaise tatti ka ganda',
  'Bhenchod ka dimaag hai sasta, har jagah gand ka naye vasta',
  'Teri behen ka bhosda hai geela, har lauda usmein karta khela',
  'Laude ke bal tera pura plan, har baat mein gand ka scam',
  'Harami ka chehra hai thoka, dekh ke aankh mein lage dhoka',
  'Teri gand se badboo ka jhada, saala sunke mare kutta pada',
  'Teri gand ka chehra hai kala, saala dekh ke lage tatti ka jala',
  'Chutiya tera baap bhi tharki, lund pe rakhta hai pura dharki',
  'Madarchod ka zindagi ka naata, har din gand mein lund ka baata',
  'Teri maa ki choot se dhool, laude ke liye hai free ka school',
  'Gandu tera dimag hai fooka, bolta jaise tatti ka jhootha',
  'Bhenchod ka muh hai chhota, har baat mein gand ka tota',
  'Teri behen ka bhosda hai thanda, har lauda usmein karta danda',
  'Lauda tera sapna hai sasta, dimag mein bas tatti ka basta',
  'Harami ka chehra hai laal, gand mein ghusa hai pura saal',
  'Teri gand pe thappad ka dhamaka, saala cheekh se toot jaye tamasha',
  'Chutmarike ka pura khandaan, har ek ke muh mein tatti ka daan',
  'Madarchod ka dil hai patthar, gand mein lund ka pura satthar',
  'Teri shakal hai kutta ka thobda, dekh ke bhage koi bhi lobda',
  'Teri maa ka choot ka jhol, har din laude ka naye bol',
  'Gandu ke pille tera nasha, tatti se bhara hai pura tasa',
  'Bhenchod ka dimaag hai dheela, har jagah tatti ka khela',
  'Teri behen ki choot ka saaz, har lauda usmein bajata raaz',
  'Laude ke bal tera pura dhoka, har baat mein gand ka thoka',
  'Harami ka baccha tu chhupa, dimag mein tatti ka pura dhuaan',
  'Teri gand se nikle awaaz, saala sunke mare kutta ka saaz',
  'Chutiya tera pura jahan, har ek ke dimag mein tatti ka daan',
  'Madarchod ka muh hai laal, bolta jaise gand ka haal',
  'Teri shakal pe tatti ka rang, dekh ke lage kutta bhi tang',
  'Teri maa ki choot ka funda, har din laude ka naye chhunda',
  'Gandu tera muh hai sookha, bolta jaise tatti ka jhootha',
  'Bhenchod ka chehra hai kala, dimag mein bas gand ka jala',
  'Teri behen ka bhosda hai chhota, har lauda usmein karta kota',
  'Lauda tera zindagi ka rona, har baat mein tatti ka sona',
  'Harami ka sapna hai ganda, dimag mein bas tatti ka banda',
  'Teri gand pe laat ka zor, saala cheekh se toot jaye chor',
  'Chutmarike ka pura raag, har jagah gand ka naye daag',
  'Madarchod ka dil hai chhupa, gand mein lund ka pura dhuaan',
  'Teri shakal hai harami ka gola, dekh ke mare kutta bhi bola',
  'Teri maa ka choot ka nasha, har din laude ka pura tasa',
  'Gandu ke bacche tera scene, tatti se bhara hai pura machine',
  'Bhenchod ka muh hai thanda, dimag mein bas gand ka ganda',
  'Teri behen ki choot ka jhol, har lauda usmein karta bol',
  'Laude ke bal tera pura plan, har baat mein gand ka scam',
  'Harami ka chehra hai sasta, dekh ke aankh mein lage vasta',
  'Teri gand se aati hai hawa, saala sunke mare kutta bhi dawa',
  'Chutiya tera pura zamana, har ek ka dimag hai tatti thikana',
  'Madarchod ka dimaag hai laal, bolta jaise gand ka haal',
  'Teri shakal pe thook ka paani, dekh ke bhage kutta bhi rani',
  'Teri maa ki choot ka gate, har din laude ka naye fate',
  'Gandu tera dimag hai chhota, tatti se bhara hai pura kota',
  'Bhenchod ka chehra hai geela, har baat mein tatti ka khela',
  'Teri behen ka bhosda hai khula, har lauda usmein ghusa bhula',
  'Lauda tera zindagi ka saaz, har jagah failata tatti ka raaz',
  'Harami ka baccha tu thoka, dimag mein bas gand ka dhoka',
  'Teri gand pe thappad ka nishaan, saala cheekh se bhar de pura makaan',
  'Chutmarike ka pura wajood, tatti se bhara hai zindagi ka mood',
  'Madarchod ka muh hai khota, bolta jaise tatti ka quota',
  'Teri shakal hai bhosdi ka thobda, dekh ke mare koi bhi lobda',
  'Teri maa ka choot ka rasta, har din laude ka pura vasta',
  'Gandu ke pille tera style, tatti se bhara hai pura pile',
  'Bhenchod ka dil hai sasta, har baat mein gand ka vasta',
  'Teri behen ki choot ka mela, har lauda usmein karta khela',
  'Lauda tera dimag se sookha, har baat mein tatti ka jhootha',
  'Harami ka chehra hai thanda, dimag mein bas gand ka ganda',
  'Teri gand se nikle dhuaan, saala sunke mare kutta huaan',
  'Chutiya tera pura sapna, har jagah tatti ka apna',
  'Madarchod ka muh hai chhupa, bolta jaise gand mein dhuaan',
  'Teri shakal pe tatti ka zor, dekh ke mare kutta bhi chor',
  'Teri maa ki choot ka paani, laude ke liye hai free ka khazana',
  'Gandu tera dimag hai geela, bolta jaise tatti ka khela',
  'Bhenchod ka chehra hai laal, dimag mein gand ka pura haal',
  'Teri behen ka bhosda hai sasta, har lauda usmein karta masta',
  'Laude ke bal tera pura raag, har jagah gand ka naye daag',
  'Harami ka sapna hai chhota, dimag mein bas tatti ka kota',
  'Teri gand pe laat ka dhamaka, saala cheekh se toot jaye tamasha',
  'Chutmarike ka pura scene, har baat mein gand ka machine',
  'Madarchod ka dil hai thoka, har baat mein gand ka dhoka',
  'Teri shakal hai suwar ka gola, dekh ke mare kutta bhi bola',
  'Teri maa ka choot ka funda, har din laude ka naye chhunda',
  'Gandu ke bacche tera nasha, tatti se bhara hai pura tasa',
  'Bhenchod ka muh hai sookha, dimag mein bas tatti ka jhootha',
  'Teri behen ki choot ka saaz, har lauda usmein bajata raaz',
  'Lauda tera zindagi ka rona, har baat mein tatti ka sona',
  'Harami ka chehra hai khota, dekh ke aankh mein lage chhota',
  'Teri gand se aati hai boo, saala sunke mare kutta bhi ro',
  'Chutiya tera pura jahan, har ek ke dimag mein tatti ka daan',
  'Madarchod ka dimaag hai geela, bolta jaise tatti ka khela',
  'Teri shakal pe thook ka rang, dekh ke lage kutta bhi tang',
  'Teri maa ki choot ka jhol, har din laude ka naye bol',
  'Gandu tera muh hai thanda, bolta jaise gand ka ganda',
  'Bhenchod ka chehra hai chhota, dimag mein bas tatti ka kota',
  'Teri behen ka bhosda hai geela, har lauda usmein karta khela',
  'Laude ke bal tera pura plan, har baat mein gand ka scam',
  'Harami ka baccha tu sasta, dimag mein bas tatti ka vasta',
  'Teri gand pe thappad ka zor, saala cheekh se toot jaye mor',
  'Chutmarike ka pura wajood, tatti se bhara hai zindagi ka mood',
  'Madarchod ka muh hai laal, bolta jaise gand ka haal',
  'Teri shakal hai harami ka thobda, dekh ke mare koi bhi lobda',
  'Teri maa ka choot ka nasha, har din laude ka pura tasa',
  'Gandu ke pille tera scene, tatti se bhara hai pura machine',
  'Bhenchod ka dil hai geela, har baat mein tatti ka khela',
  'Teri behen ki choot ka gate, har lauda usmein karta fate',
  'Lauda tera dimag se chhota, har baat mein tatti ka kota',
  'Harami ka chehra hai sookha, dimag mein bas gand ka jhootha',
  'Teri gand se nikle hawa, saala sunke mare kutta bhi dawa',
  'Teri gand ka rang hai peela, saala dekh ke lage tatti ka khela',
  'Chutiya tera baap ka plan, lund pe rakhta hai pura scam',
  'Madarchod ka zindagi ka khel, gand mein lund ka roz ka mel',
  'Teri maa ki choot se farta, har din laude ka naye darta',
  'Gandu tera dimag hai latka, bolta jaise tatti ka patka',
  'Bhenchod ka muh hai phoota, har baat mein gand ka jhootha',
  'Teri behen ka bhosda hai kaala, har lauda usmein karta jhaala',
  'Lauda tera sapna hai toota, dimag mein bas tatti ka loota',
  'Harami ka chehra hai peela, dekh ke lage aankh ka cheela',
  'Teri gand pe laat ka tamasha, saala cheekh se toot jaye khwasha',
  'Chutmarike ka pura jadoo, tatti se bhara hai zindagi ka mood',
  'Madarchod ka dil hai kankar, gand mein lund ka pura chakkar',
  'Teri shakal hai kutta ka gola, dekh ke bhage koi bhi tola',
  'Teri maa ka choot ka chaska, har din laude ka naye maska',
  'Gandu ke pille tera josh, tatti se bhara hai pura tosh',
  'Bhenchod ka dimaag hai phusphus, har jagah gand ka naye bus',
  'Teri behen ki choot ka chhala, har lauda usmein karta jala',
  'Laude ke bal tera pura khel, har baat mein gand ka mel',
  'Harami ka baccha tu latka, dimag mein tatti ka pura katka',
  'Teri gand se nikle fasaad, saala sunke mare kutta barbaad',
  'Chutiya tera pura parivaar, har ek ke dimag mein tatti ka bazaar',
  'Madarchod ka muh hai latka, bolta jaise gand mein katka',
  'Teri shakal pe tatti ka chhapa, dekh ke lage kutta bhi thappa',
  'Teri maa ki choot ka gola, har din laude ka naye bola',
  'Gandu tera muh hai phusphus, bolta jaise tatti ka bus',
  'Bhenchod ka chehra hai latka, dimag mein bas gand ka katka',
  'Teri behen ka bhosda hai phoola, har lauda usmein ghusa bhoola',
  'Lauda tera zindagi ka chhota, har baat mein tatti ka kota',
  'Harami ka sapna hai peela, dimag mein bas gand ka cheela',
  'Teri gand pe thappad ka jhatka, saala cheekh se toot jaye latka',
  'Chutmarike ka pura chaska, har jagah gand ka naye maska',
  'Madarchod ka dil hai phoota, gand mein lund ka pura jhootha',
  'Teri shakal hai harami ka chhala, dekh ke mare kutta bhi jala',
  'Teri maa ka choot ka chhappa, har din laude ka naye thappa',
  'Gandu ke bacche tera khel, tatti se bhara hai pura mel',
  'Bhenchod ka muh hai peela, dimag mein bas tatti ka cheela',
  'Teri behen ki choot ka latka, har lauda usmein karta katka',
  'Laude ke bal tera pura josh, har baat mein gand ka tosh',
  'Harami ka chehra hai phusphus, dekh ke aankh mein lage bus',
  'Teri gand se aati hai farta, saala sunke mare kutta darta',
  'Chutiya tera pura jadoo, har ek ke dimag mein tatti ka mood',
  'Madarchod ka dimaag hai chhapa, bolta jaise gand ka thappa',
  'Teri shakal pe thook ka chhala, dekh ke bhage kutta bhi jala',
  'Teri maa ki choot ka phoola, har din laude ka ghusa bhoola',
  'Gandu tera dimag hai latka, bolta jaise tatti ka katka',
  'Bhenchod ka chehra hai phoota, dimag mein bas gand ka jhootha',
  'Teri behen ka bhosda hai chhota, har lauda usmein karta kota',
  'Lauda tera zindagi ka tamasha, har baat mein tatti ka khwasha',
  'Harami ka baccha tu phusphus, dimag mein bas gand ka bus',
  'Teri gand pe laat ka chaska, saala cheekh se toot jaye maska',
  'Chutmarike ka pura parivaar, tatti se bhara hai pura bazaar',
  'Madarchod ka muh hai phoola, bolta jaise gand mein bhoola',
  'Teri shakal hai bhosdi ka chhapa, dekh ke mare koi bhi thappa',
  'Teri maa ka choot ka jadoo, har din laude ka naye mood',
  'Gandu ke pille tera chhala, tatti se bhara hai pura jala',
  'Bhenchod ka dimaag hai peela, har baat mein gand ka cheela',
  'Teri behen ki choot ka phusphus, har lauda usmein karta bus',
  'Laude ke bal tera pura chaska, har baat mein gand ka maska',
  'Harami ka chehra hai latka, dekh ke aankh mein lage katka',
  'Teri gand se nikle chhota, saala sunke mare kutta kota',
  'Chutiya tera pura khel, har jagah gand ka naye mel',
  'Madarchod ka dil hai chhala, bolta jaise tatti ka jala',
  'Teri shakal pe tatti ka tamasha, dekh ke lage kutta khwasha',
  'Teri maa ki choot ka latka, har din laude ka naye katka',
  'Gandu tera muh hai chhapa, bolta jaise gand ka thappa',
  'Bhenchod ka chehra hai chhota, dimag mein bas tatti ka kota',
  'Teri behen ka bhosda hai peela, har lauda usmein karta cheela',
  'Lauda tera zindagi ka jadoo, har baat mein tatti ka mood',
  'Harami ka sapna hai phusphus, dimag mein bas gand ka bus',
  'Teri gand pe thappad ka phoola, saala cheekh se toot jaye bhoola',
  'Chutmarike ka pura josh, tatti se bhara hai pura tosh',
  'Madarchod ka muh hai latka, bolta jaise tatti ka katka',
  'Teri shakal hai suwar ka chhala, dekh ke mare kutta bhi jala',
  'Teri maa ka choot ka chaska, har din laude ka naye maska',
  'Gandu ke bacche tera tamasha, tatti se bhara hai pura khwasha',
  'Bhenchod ka dimaag hai phoola, dimag mein bas gand mein bhoola',
  'Teri behen ki choot ka jadoo, har lauda usmein karta mood',
  'Laude ke bal tera pura parivaar, har baat mein gand ka bazaar',
  'Harami ka chehra hai phoota, dekh ke aankh mein lage jhootha',
  'Teri gand se aati hai latka, saala sunke mare kutta katka',
  'Chutiya tera pura chhala, har jagah tatti ka jala',
  'Madarchod ka dil hai peela, bolta jaise gand ka cheela',
  'Teri shakal pe thook ka jadoo, dekh ke bhage kutta mood',
  'Teri maa ki choot ka phusphus, har din laude ka naye bus',
  'Gandu tera dimag hai chhota, bolta jaise tatti ka kota',
  'Bhenchod ka muh hai tamasha, dimag mein bas gand ka khwasha',
  'Teri behen ka bhosda hai latka, har lauda usmein karta katka',
  'Lauda tera zindagi ka chaska, har baat mein gand ka maska',
  'Harami ka baccha tu chhala, dimag mein bas tatti ka jala',
  'Teri gand pe laat ka phoola, saala cheekh se toot jaye bhoola',
  'Chutmarike ka pura khel, tatti se bhara hai pura mel',
  'Madarchod ka chehra hai phusphus, bolta jaise gand ka bus',
  'Teri shakal hai harami ka tamasha, dekh ke mare kutta khwasha',
  'Teri maa ka choot ka jadoo, har din laude ka naye mood',
  'Gandu ke pille tera latka, tatti se bhara hai pura katka',
  'Bhenchod ka dimaag hai chhapa, har baat mein gand ka thappa',
  'Teri behen ki choot ka chaska, har lauda usmein karta maska',
  'Laude ke bal tera pura jadoo, har baat mein tatti ka mood',
  'Harami ka chehra hai chhota, dekh ke aankh mein lage kota',
  'Teri gand se nikle phusphus, saala sunke mare kutta bus',
  'Teri gand ka suraj hai dooba, saala harami tera muh hai khooba',
  'Chutiya tera baap ka chhota, lund pe rakhta hai pura kota',
  'Madarchod ka zindagi ka saaz, gand mein lund ka roz ka raaz',
  'Teri maa ki choot se chhidi, har din laude ki naye phidi',
  'Gandu tera dimag hai bhatka, bolta jaise tatti ka latka',
  'Bhenchod ka muh hai chhidra, har baat mein gand ka gidra',
  'Teri behen ka bhosda hai ghooma, har lauda usmein karta dhooma',
  'Lauda tera sapna hai khiska, dimag mein bas tatti ka siska',
  'Harami ka chehra hai bheega, dekh ke lage aankh ka teega',
  'Teri gand pe laat ka sailaab, saala cheekh se toot jaye gulaab',
  'Chutmarike ka pura jatan, tatti se bhara hai zindagi ka ghatan',
  'Madarchod ka dil hai bikhra, gand mein lund ka pura sikra',
  'Teri shakal hai gadhe ka dhaaga, dekh ke bhage koi bhi laaga',
  'Teri maa ka choot ka chhida, har din laude ka naye phida',
  'Gandu ke pille tera jatan, tatti se bhara hai pura ghatan',
  'Bhenchod ka dimaag hai bhoosa, har jagah gand ka naye toosa',
  'Teri behen ki choot ka sailaab, har lauda usmein karta gulaab',
  'Laude ke bal tera pura saaz, har baat mein tatti ka raaz',
  'Harami ka baccha tu bhatka, dimag mein tatti ka pura latka',
  'Teri gand se nikle chingaari, saala sunke mare kutta bhaari',
  'Chutiya tera pura vichar, har ek ke dimag mein tatti ka bazaar',
  'Madarchod ka muh hai bheega, bolta jaise gand ka teega',
  'Teri shakal pe tatti ka sailaab, dekh ke lage kutta gulaab',
  'Teri maa ki choot ka bhatka, har din laude ka naye latka',
  'Gandu tera muh hai bikhra, bolta jaise tatti ka sikra',
  'Bhenchod ka chehra hai bhoosa, dimag mein bas gand ka toosa',
  'Teri behen ka bhosda hai bikhra, har lauda usmein karta sikra',
  'Lauda tera zindagi ka chhida, har baat mein tatti ka phida',
  'Harami ka sapna hai bheega, dimag mein bas gand ka teega',
  'Teri gand pe thappad ka bhoosa, saala cheekh se toot jaye toosa',
  'Chutmarike ka pura vichar, tatti se bhara hai pura bazaar',
  'Madarchod ka dil hai khiska, gand mein lund ka pura siska',
  'Teri shakal hai harami ka chhida, dekh ke mare kutta phida',
  'Teri maa ka choot ka sailaab, har din laude ka naye gulaab',
  'Gandu ke bacche tera saaz, tatti se bhara hai pura raaz',
  'Bhenchod ka muh hai bhatka, dimag mein bas gand ka latka',
  'Teri behen ki choot ka bikhra, har lauda usmein karta sikra',
  'Laude ke bal tera pura jatan, har baat mein tatti ka ghatan',
  'Harami ka chehra hai khiska, dekh ke lage aankh ka siska',
  'Teri gand se aati hai bhaap, saala sunke mare kutta paap',
  'Chutiya tera pura saaz, har ek ke dimag mein tatti ka raaz',
  'Madarchod ka dimaag hai bikhra, bolta jaise gand ka sikra',
  'Teri shakal pe thook ka bhoosa, dekh ke bhage kutta toosa',
  'Teri maa ki choot ka bheega, har din laude ka naye teega',
  'Gandu tera dimag hai chhidra, bolta jaise tatti ka gidra',
  'Bhenchod ka chehra hai chhida, dimag mein bas gand ka phida',
  'Teri behen ka bhosda hai bhatka, har lauda usmein karta latka',
  'Lauda tera zindagi ka bhoosa, har baat mein tatti ka toosa',
  'Harami ka baccha tu khiska, dimag mein bas gand ka siska',
  'Teri gand pe laat ka bikhra, saala cheekh se toot jaye sikra',
  'Chutmarike ka pura saaz, tatti se bhara hai pura raaz',
  'Madarchod ka muh hai bhoosa, bolta jaise gand ka toosa',
  'Teri shakal hai bhosdi ka bhatka, dekh ke mare kutta latka',
  'Teri maa ka choot ka khiska, har din laude ka naye siska',
  'Gandu ke pille tera bheega, tatti se bhara hai pura teega',
  'Bhenchod ka dimaag hai chhida, har baat mein gand ka phida',
  'Teri behen ki choot ka bhoosa, har lauda usmein karta toosa',
  'Laude ke bal tera pura vichar, har baat mein tatti ka bazaar',
  'Harami ka chehra hai bikhra, dekh ke aankh mein lage sikra',
  'Teri gand se nikle bhaapna, saala sunke mare kutta apna',
  'Chutiya tera pura jatan, har jagah tatti ka ghatan',
  'Madarchod ka dil hai bhatka, gand mein lund ka pura latka',
  'Teri shakal pe tatti ka bheega, dekh ke lage kutta teega',
  'Teri maa ki choot ka bikhra, har din laude ka naye sikra',
  'Gandu tera muh hai khiska, bolta jaise tatti ka siska',
  'Bhenchod ka chehra hai bhatka, dimag mein bas gand ka latka',
  'Teri behen ka bhosda hai chhida, har lauda usmein karta phida',
  'Lauda tera zindagi ka bhatka, har baat mein tatti ka latka',
  'Harami ka sapna hai bhoosa, dimag mein bas gand ka toosa',
  'Teri gand pe thappad ka sailaab, saala cheekh se toot jaye gulaab',
  'Chutmarike ka pura bikhra, tatti se bhara hai pura sikra',
  'Madarchod ka muh hai chhida, bolta jaise gand ka phida',
  'Teri shakal hai suwar ka bheega, dekh ke mare kutta teega',
  'Teri maa ka choot ka bhatka, har din laude ka naye latka',
  'Gandu ke bacche tera chhidra, tatti se bhara hai pura gidra',
  'Bhenchod ka dimaag hai khiska, har baat mein gand ka siska',
  'Teri behen ki choot ka bikhra, har lauda usmein karta sikra',
  'Laude ke bal tera pura saaz, har baat mein tatti ka raaz',
  'Harami ka chehra hai chhida, dekh ke aankh mein lage phida',
  'Teri gand se aati hai chingaari, saala sunke mare kutta bhaari',
  'Chutiya tera pura bhoosa, har ek ke dimag mein tatti ka toosa',
  'Madarchod ka dil hai bheega, gand mein lund ka pura teega',
  'Teri shakal pe thook ka bhatka, dekh ke bhage kutta latka',
  'Teri maa ki choot ka khiska, har din laude ka naye siska',
  'Gandu tera dimag hai bikhra, bolta jaise tatti ka sikra',
  'Bhenchod ka muh hai bhoosa, dimag mein bas gand ka toosa',
  'Teri behen ka bhosda hai bhatka, har lauda usmein karta latka',
  'Lauda tera zindagi ka chhida, har baat mein tatti ka phida',
  'Harami ka baccha tu bheega, dimag mein bas gand ka teega',
  'Teri gand pe laat ka bhoosa, saala cheekh se toot jaye toosa',
  'Chutmarike ka pura chhidra, tatti se bhara hai pura gidra',
  'Madarchod ka chehra hai khiska, bolta jaise gand ka siska',
  'Teri shakal hai harami ka bikhra, dekh ke mare kutta sikra',
  'Teri maa ka choot ka bheega, har din laude ka naye teega',
  'Gandu ke pille tera bhatka, tatti se bhara hai pura latka',
  'Bhenchod ka dimaag hai chhida, har baat mein gand ka phida',
  'Teri behen ki choot ka sailaab, har lauda usmein karta gulaab',
  'Laude ke bal tera pura jatan, har baat mein tatti ka ghatan',
  'Harami ka chehra hai bhatka, dekh ke aankh mein lage latka',
  'Teri gand se nikle khiska, saala sunke mare kutta siska',
  'Chutiya tera pura saaz, har jagah tatti ka raaz',
  'Madarchod ka muh hai bikhra, bolta jaise gand ka sikra',
  'Teri shakal pe tatti ka chhidra, dekh ke lage kutta gidra',
  'Teri maa ki choot ka bhoosa, har din laude ka naye toosa',
  'Gandu tera dimag hai bheega, bolta jaise tatti ka teega',
  'Bhenchod ka chehra hai khiska, dimag mein bas gand ka siska',
  'Teri behen ka bhosda hai bikhra, har lauda usmein karta sikra',
  'Lauda tera zindagi ka bhatka, har baat mein tatti ka latka',
  'Harami ka sapna hai chhidra, dimag mein bas gand ka gidra',
  'Teri gand pe thappad ka bhatka, saala cheekh se toot jaye latka',
  'Chutmarike ka pura bheega, tatti se bhara hai pura teega',
  'Madarchod ka dil hai bhoosa, gand mein lund ka pura toosa',
  'Teri shakal hai bhosdi ka khiska, dekh ke mare kutta siska',
  'Teri maa ka choot ka chhidra, har din laude ka naye gidra',
  'Gandu ke bacche tera bikhra, tatti se bhara hai pura sikra',
  'Bhenchod ka muh hai bhatka, dimag mein bas gand ka latka',
  'Teri behen ki choot ka bhoosa, har lauda usmein karta toosa',
  'Laude ke bal tera pura chhidra, har baat mein tatti ka gidra',
  'Harami ka chehra hai bheega, dekh ke aankh mein lage teega',
  'Teri gand se aati hai bikhra, saala sunke mare kutta sikra',
  'Chutiya tera pura jatan, har ek ke dimag mein tatti ka ghatan',
  'Madarchod ka dimaag hai khiska, bolta jaise gand ka siska',
  'Teri shakal pe thook ka bhoosa, dekh ke bhage kutta toosa',
  'Teri maa ki choot ka bhatka, har din laude ka naye latka',
  'Gandu tera muh hai chhidra, bolta jaise tatti ka gidra',
  'Bhenchod ka chehra hai bikhra, dimag mein bas gand ka sikra',
  'Teri behen ka bhosda hai bheega, har lauda usmein karta teega',
  'Lauda tera zindagi ka sailaab, har baat mein tatti ka gulaab',
  'Harami ka baccha tu khiska, dimag mein bas gand ka siska',
  'Teri gand pe laat ka chhidra, saala cheekh se toot jaye gidra',
  'Chutmarike ka pura saaz, tatti se bhara hai pura raaz',
  'Madarchod ka muh hai bhoosa, bolta jaise gand ka toosa',
  'Teri shakal hai suwar ka bhatka, dekh ke mare kutta latka',
  'Teri maa ka choot ka khiska, har din laude ka naye siska',
  'Gandu ke pille tera bheega, tatti se bhara hai pura teega',
  'Bhenchod ka dimaag hai bikhra, har baat mein gand ka sikra',
  'Teri behen ki choot ka bhatka, har lauda usmein karta latka',
  'Laude ke bal tera pura vichar, har baat mein tatti ka bazaar',
  'Harami ka chehra hai chhidra, dekh ke aankh mein lage gidra',
  'Teri gand se nikle bhoosa, saala sunke mare kutta toosa',
  'Chutiya tera pura bikhra, har jagah tatti ka sikra',
  'Madarchod ka dil hai bhatka, gand mein lund ka pura latka',
  'Teri shakal pe tatti ka khiska, dekh ke lage kutta siska',
  'Teri maa ki choot ka bheega, har din laude ka naye teega',
  'Gandu tera dimag hai chhidra, bolta jaise tatti ka gidra',
  'Bhenchod ka muh hai bhoosa, dimag mein bas gand ka toosa',
  'Teri behen ka bhosda hai bhatka, har lauda usmein karta latka',
  'Lauda tera zindagi ka bikhra, har baat mein tatti ka sikra',
  'Harami ka sapna hai khiska, dimag mein bas gand ka siska',
  'Teri gand pe thappad ka bheega, saala cheekh se toot jaye teega',
  'Chutmarike ka pura chhidra, tatti se bhara hai pura gidra',
  'Madarchod ka chehra hai bhatka, bolta jaise gand ka latka',
  'Teri shakal hai harami ka bhoosa, dekh ke mare kutta toosa',
  'Teri maa ka choot ka sailaab, har din laude ka naye gulaab',
  'Gandu ke bacche tera khiska, tatti se bhara hai pura siska',
  'Bhenchod ka dimaag hai bheega, har baat mein gand ka teega',
  'Teri behen ki choot ka bikhra, har lauda usmein karta sikra',
  'Laude ke bal tera pura saaz, har baat mein tatti ka raaz',
  'Harami ka chehra hai bikhra, dekh ke aankh mein lage sikra',
  'Teri gand se aati hai chhidra, saala sunke mare kutta gidra',
  'Chutiya tera pura vichar, har ek ke dimag mein tatti ka bazaar',
  'Madarchod ka muh hai khiska, bolta jaise gand ka siska',
  'Teri shakal pe thook ka bhatka, dekh ke bhage kutta latka',
  'Teri maa ki choot ka bhoosa, har din laude ka naye toosa',
  'Gandu tera dimag hai bikhra, bolta jaise tatti ka sikra',
  'Bhenchod ka chehra hai chhidra, dimag mein bas gand ka gidra',
  'Teri behen ka bhosda hai khiska, har lauda usmein karta siska',
  'Lauda tera zindagi ka bheega, har baat mein tatti ka teega',
  'Harami ka baccha tu bhatka, dimag mein bas gand ka latka',
  'Teri gand pe laat ka bikhra, saala cheekh se toot jaye sikra',
  'Hari Hari ghas pe chidiya ka ghosla sale teri maa bhosda'
];
export default gaali;
