name: imgcmp
on:
  push:
    branches:
      - main
      - master
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: saranshbalyan-1234/imgcmp@v2.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}