name: imgcmp
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: saranshbalyan-1234/imgcmp@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}