name: imgcmp
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  imgcmp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: saranshbalyan-1234/imgcmp@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}